<a href="https://colab.research.google.com/github/Danishzaman-0786/simple_NN_Train_/blob/main/by%20using%20nn%20mudule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import torch as t

In [17]:
from sklearn.model_selection import train_test_split as spt

In [23]:
from sklearn.preprocessing import LabelEncoder as l

In [24]:
from sklearn.preprocessing import StandardScaler as s

In [11]:
v=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")


In [12]:
v

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [10]:
v=v.drop(columns=['id','Unnamed: 32'])


In [15]:
v=v.drop(columns=['id','Unnamed: 32'])

In [16]:
v

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [18]:
x_train,x_test,y_train,y_test=spt(v.iloc[:,1:],v.iloc[:,0])

In [19]:
y_train

424    B
540    B
233    M
0      M
489    M
      ..
159    B
436    B
397    B
428    B
125    B
Name: diagnosis, Length: 426, dtype: object

In [26]:
std=s()

In [28]:
x_train,x_test=std.fit_transform(x_train),std.fit_transform(x_test)

In [29]:
label=l()

In [30]:
y_train,y_test=label.fit_transform(y_train),label.fit_transform(y_test)

In [31]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1])

In [32]:
import torch as t

In [33]:
x_train_t,x_test_t,y_train_t,y_test_t=t.from_numpy(x_train),t.from_numpy(x_test),t.from_numpy(y_train),t.from_numpy(y_test)

In [34]:
x_train_t

tensor([[-1.2814, -0.0692, -1.2733,  ..., -1.1284,  0.4239, -0.2384],
        [-0.7828, -1.1379, -0.7627,  ..., -0.7731, -0.9119, -0.1719],
        [ 1.7046,  1.9152,  1.6360,  ...,  0.5559, -0.7455, -0.0687],
        ...,
        [-0.4334, -0.4483, -0.4254,  ..., -0.5629, -1.4373, -0.7471],
        [-0.8965, -0.6401, -0.9305,  ..., -1.2115, -0.8287, -0.7311],
        [-0.1422, -0.5053, -0.2091,  ..., -1.0498, -0.8580, -0.6785]],
       dtype=torch.float64)

In [35]:
import torch.nn as nn

In [74]:
class Nn(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.l1=nn.Linear(features,1)
    self.sig_=nn.Sigmoid()
  def forward(self,x):
    z=self.l1(x)
    y_pred=self.sig_(z)
    return y_pred
  def loss_(self,y,y_pred):
    epsilen=1e-7
    y_pred=t.clamp(y_pred,epsilen,1-epsilen)
    loss=-(y*t.log(y_pred)+(1-y)*(1-t.log(y_pred)))
    loss=loss.mean()
    return loss

In [75]:
model=Nn(x_train_t.shape[1])

In [76]:
model

Nn(
  (l1): Linear(in_features=30, out_features=1, bias=True)
  (sig_): Sigmoid()
)

In [77]:
x_train_t.shape[1]

30

In [78]:
!pip install torchinfo


In [79]:
from torchinfo import summary

In [80]:
x_train_t,x_test_t=x_train_t.to(t.float32),x_test_t.to(t.float32)

In [81]:
model(x_train_t)

tensor([[0.5744],
        [0.4588],
        [0.6450],
        [0.2305],
        [0.2427],
        [0.7719],
        [0.3718],
        [0.3910],
        [0.2702],
        [0.3360],
        [0.5235],
        [0.5853],
        [0.2984],
        [0.4826],
        [0.3673],
        [0.5805],
        [0.5388],
        [0.4932],
        [0.4568],
        [0.5230],
        [0.4615],
        [0.3481],
        [0.4288],
        [0.5055],
        [0.2874],
        [0.5175],
        [0.6527],
        [0.3445],
        [0.4660],
        [0.4375],
        [0.5662],
        [0.3856],
        [0.4961],
        [0.4862],
        [0.3997],
        [0.8296],
        [0.5435],
        [0.4730],
        [0.4843],
        [0.5168],
        [0.4909],
        [0.3922],
        [0.4169],
        [0.5303],
        [0.5247],
        [0.4012],
        [0.2938],
        [0.6745],
        [0.3911],
        [0.4089],
        [0.3340],
        [0.3862],
        [0.3602],
        [0.4399],
        [0.4291],
        [0

In [82]:
summary(model,input_size=(x_train_t.shape))

Layer (type:depth-idx)                   Output Shape              Param #
Nn                                       [426, 1]                  --
├─Linear: 1-1                            [426, 1]                  31
├─Sigmoid: 1-2                           [426, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.05

In [103]:
lr=0.0001

In [104]:
epochs=50

In [105]:
for i in range(epochs):
  #forward
  y_pred=model(x_train_t)
  #loss
  loss1=model.loss_(y_train_t,y_pred)
  #backpro..
  loss1.backward()
  with t.no_grad():
    model.l1.weight-=lr*model.l1.weight.grad
    model.l1.bias-=lr*model.l1.bias.grad
  # Zero gradients after update
  model.l1.weight.grad.zero_()
  model.l1.bias.grad.zero_()
  print(f'epoch:{i} loss:{loss1}')


epoch:0 loss:-2.9970831871032715
epoch:1 loss:-2.9970831871032715
epoch:2 loss:-2.9970836639404297
epoch:3 loss:-2.9970836639404297
epoch:4 loss:-2.9970836639404297
epoch:5 loss:-2.997083902359009
epoch:6 loss:-2.997083902359009
epoch:7 loss:-2.997083902359009
epoch:8 loss:-2.997084379196167
epoch:9 loss:-2.997084617614746
epoch:10 loss:-2.997084617614746
epoch:11 loss:-2.997084617614746
epoch:12 loss:-2.9970850944519043
epoch:13 loss:-2.9970850944519043
epoch:14 loss:-2.9970850944519043
epoch:15 loss:-2.9970850944519043
epoch:16 loss:-2.9970850944519043
epoch:17 loss:-2.9970853328704834
epoch:18 loss:-2.9970858097076416
epoch:19 loss:-2.9970860481262207
epoch:20 loss:-2.9970860481262207
epoch:21 loss:-2.9970860481262207
epoch:22 loss:-2.9970860481262207
epoch:23 loss:-2.9970862865448
epoch:24 loss:-2.9970862865448
epoch:25 loss:-2.9970862865448
epoch:26 loss:-2.997086763381958
epoch:27 loss:-2.997086763381958
epoch:28 loss:-2.997086763381958
epoch:29 loss:-2.997087001800537
epoch:30 l

In [107]:
model(x_test_t)

tensor([[3.9592e-12],
        [3.6250e-06],
        [4.1545e-14],
        [7.5215e-18],
        [6.4895e-11],
        [1.6121e-19],
        [2.3602e-15],
        [2.4490e-14],
        [9.1741e-15],
        [1.0000e+00],
        [5.9901e-14],
        [1.1094e-12],
        [4.0760e-11],
        [1.8312e-14],
        [7.1945e-13],
        [9.9095e-13],
        [3.8242e-07],
        [5.3245e-07],
        [2.9762e-20],
        [1.1241e-04],
        [1.4885e-15],
        [1.0000e+00],
        [3.2441e-13],
        [1.4649e-23],
        [5.8097e-17],
        [1.9495e-16],
        [3.1347e-20],
        [6.3850e-22],
        [4.6329e-13],
        [9.9713e-01],
        [9.5725e-17],
        [1.0000e+00],
        [3.9859e-06],
        [1.0000e+00],
        [4.2378e-01],
        [5.0054e-13],
        [3.5363e-17],
        [1.6771e-18],
        [1.0000e+00],
        [1.7574e-14],
        [1.0407e-07],
        [2.4763e-19],
        [1.0069e-18],
        [3.2363e-05],
        [1.7744e-16],
        [2

In [109]:
with t.no_grad():
  y_pred=model(x_test_t)
  y_pred=(y_pred>0.5).int()
print(y_pred)

tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],

In [110]:
#accuracy
with t.no_grad():
  accuracy=(y_pred==y_train_t).float().mean()
print(f"accuracy:={accuracy}")

accuracy:=0.5614104270935059
