<a href="https://colab.research.google.com/github/Danishzaman-0786/simple_NN_Train_/blob/main/simple_NN_train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [523]:
import pandas as pd

In [524]:
v=pd.read_csv("https://raw.githubusercontent.com/Danishzaman-0786/Placement_prediction/refs/heads/main/placement.csv")

In [525]:
v

cgpa  placement_exam_marks  placed
0    7.19                  26.0       1
1    7.46                  38.0       1
2    7.54                  40.0       1
3    6.42                   8.0       1
4    7.23                  17.0       0
..    ...                   ...     ...
995  8.87                  44.0       1
996  9.12                  65.0       1
997  4.89                  34.0       0
998  8.62                  46.0       1
999  4.90                  10.0       1

[1000 rows x 3 columns]

In [526]:
v=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [527]:
v

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [528]:
v.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [529]:
x=pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})

In [530]:
x

a  b
0  1  4
1  2  5
2  3  6

In [531]:
x.drop(columns='a')

b
0  4
1  5
2  6

In [532]:
v=v.drop(columns=['id','Unnamed: 32'])

In [533]:
v

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0           M        17.99         10.38          122.80     1001.0   
1           M        20.57         17.77          132.90     1326.0   
2           M        19.69         21.25          130.00     1203.0   
3           M        11.42         20.38           77.58      386.1   
4           M        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564         M        21.56         22.39          142.00     1479.0   
565         M        20.13         28.25          131.20     1261.0   
566         M        16.60         28.08          108.30      858.1   
567         M        20.60         29.33          140.10     1265.0   
568         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...         

In [534]:
x_train,x_test,y_train,y_test=train_test_split(v.iloc[:,1:],v.iloc[:,0],test_size=0.2)

In [535]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
419       11.160         21.41           70.95      380.3          0.10180   
58        13.050         19.31           82.61      527.2          0.08060   
35        16.740         21.59          110.10      869.5          0.09610   
542       14.740         25.42           94.70      668.6          0.08275   
81        13.340         15.86           86.49      520.0          0.10780   
..           ...           ...             ...        ...              ...   
548        9.683         19.34           61.05      285.7          0.08491   
388       11.270         15.50           73.38      392.0          0.08365   
26        14.580         21.53           97.41      644.8          0.10540   
470        9.667         18.49           61.49      289.1          0.08946   
501       13.820         24.49           92.33      595.9          0.11620   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
419           0.05978        0.008955             0.010760         0.1615   
58            0.03789        0.000692             0.004167         0.1819   
35            0.13360        0.134800             0.060180         0.1896   
542           0.07214        0.041050             0.030270         0.1840   
81            0.15350        0.116900             0.069870         0.1942   
..                ...             ...                  ...            ...   
548           0.05030        0.023370             0.009615         0.1580   
388           0.11140        0.100700             0.027570         0.1810   
26            0.18680        0.142500             0.087830         0.2252   
470           0.06258        0.029480             0.015140         0.2238   
501           0.16810        0.135700             0.067590         0.2275   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
419                 0.06144  ...         12.36          28.92   
58                  0.05501  ...         14.23          22.25   
35                  0.05656  ...         20.01          29.02   
542                 0.05680  ...         16.51          32.29   
81                  0.06902  ...         15.53          23.19   
..                      ...  ...           ...            ...   
548                 0.06235  ...         10.93          25.59   
388                 0.07252  ...         12.04          18.93   
26                  0.06924  ...         17.62          33.21   
470                 0.06413  ...         11.14          25.62   
501                 0.07237  ...         16.01          32.94   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
419            79.26       458.0            0.1282            0.11080   
58             90.24       624.1            0.1021            0.06191   
35            133.50      1229.0            0.1563            0.38350   
542           107.40       826.4            0.1060            0.13760   
81             96.66       614.9            0.1536            0.47910   
..               ...         ...               ...                ...   
548            69.10       364.2            0.1199            0.09546   
388            79.73       450.0            0.1102            0.28090   
26            122.40       896.9            0.1525            0.66430   
470            70.88       385.2            0.1234            0.15420   
501           106.00       788.0            0.1794            0.39660   

     concavity_worst  concave points_worst  symmetry_worst  \
419         0.035820               0.04306          0.2976   
58          0.001845               0.01111          0.2439   
35          0.540900               0.18130          0.4863   
542         0.161100               0.10950          0.2722   
81          0.485800               0.17080          0.3527   
..               ...                   ...             ...   
548         0.093500               0.03846         

In [536]:
import torch as t
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [537]:
scaler=StandardScaler()

In [538]:
x_train=scaler.fit_transform(x_train)

In [539]:
x_test=scaler.transform(x_test)

In [540]:
x_train

array([[-0.86493204,  0.50683514, -0.88864814, ..., -1.10912127,
         0.14435895, -0.68515771],
       [-0.3340366 ,  0.01407374, -0.41213257, ..., -1.59770313,
        -0.74582969, -1.14272294],
       [ 0.70247353,  0.54907183,  0.71131623, ...,  1.00485545,
         3.27245201,  0.14328772],
       ...,
       [ 0.09573589,  0.53499293,  0.19270709, ...,  2.36279189,
         2.27948554,  2.40203597],
       [-1.28431134, -0.17833785, -1.27525511, ..., -0.76443786,
         0.47258493,  0.08348603],
       [-0.11774587,  1.22955185, -0.01490004, ...,  0.55832681,
         1.26331116,  1.89728775]])

In [541]:
y_train

419    B
58     B
35     M
542    B
81     B
      ..
548    B
388    B
26     M
470    B
501    M
Name: diagnosis, Length: 455, dtype: object

In [542]:
label_encoder=LabelEncoder()

In [543]:
y_train=label_encoder.fit_transform(y_train)
y_test=label_encoder.fit_transform(y_test)

In [544]:
y_test


array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0])

# #**Now** we convert numpy to torch


In [545]:
import torch as t


In [546]:
x_train=t.from_numpy(x_train)
x_test=t.from_numpy(x_test)
y_train=t.from_numpy(y_train)
y_test=t.from_numpy(y_test)

In [547]:
x_train

tensor([[-0.8649,  0.5068, -0.8886,  ..., -1.1091,  0.1444, -0.6852],
        [-0.3340,  0.0141, -0.4121,  ..., -1.5977, -0.7458, -1.1427],
        [ 0.7025,  0.5491,  0.7113,  ...,  1.0049,  3.2725,  0.1433],
        ...,
        [ 0.0957,  0.5350,  0.1927,  ...,  2.3628,  2.2795,  2.4020],
        [-1.2843, -0.1783, -1.2753,  ..., -0.7644,  0.4726,  0.0835],
        [-0.1177,  1.2296, -0.0149,  ...,  0.5583,  1.2633,  1.8973]],
       dtype=torch.float64)

In [548]:
y_train.shape

torch.Size([455])

In [549]:
class NN():
  def __init__(self,x):
    self.w=t.rand(x.shape[1],1,dtype=t.float64,requires_grad=True)
    self.b=t.zeros(1,dtype=t.float64,requires_grad=True)
  def forward_pass(self,x):
    z1=t.matmul(x,self.w)+self.b
    y_pred= t.sigmoid(z1)
    return y_pred
  def loss_(self,y,y_pred):
    e=1e-7
    y_pred=t.clamp(y_pred,e,1-e)
    loss= -(y*t.log(y_pred)-(1-y)*(1-t.log(y_pred))).mean()
    return loss
  def y_pred(self,x_test):
       y1=model.w*x_test+self.b
       return y1




In [580]:
lr_=t.tensor(0.01)

In [581]:
epochs=25


**#training pipeline**

In [582]:
model=NN(x_train)

In [583]:
model

In [584]:
class A:
  def __init__(self,x):
    self.c=2+x

In [585]:
A(1).c

3

In [586]:
model.b

tensor([0.], dtype=torch.float64, requires_grad=True)

In [587]:
model.w

tensor([[0.3144],
        [0.1796],
        [0.8709],
        [0.8577],
        [0.4999],
        [0.2853],
        [0.3452],
        [0.1344],
        [0.2941],
        [0.4941],
        [0.9224],
        [0.6632],
        [0.2050],
        [0.9758],
        [0.8452],
        [0.8806],
        [0.5275],
        [0.9431],
        [0.9041],
        [0.4596],
        [0.3674],
        [0.1247],
        [0.2759],
        [0.6597],
        [0.0387],
        [0.2449],
        [0.5287],
        [0.2426],
        [0.8426],
        [0.0418]], dtype=torch.float64, requires_grad=True)

#here is we do 4 step for traing the NN
#1:-forwar pass
#2:-we find y_pred
#3:-calculate the loss
#4:-backward pass

#it is all process in loo with epochs

In [594]:
for i in range(epochs):
  y_pred=model.forward_pass(x_train)
 # print(y_pred)
  loss=model.loss_(y_train,y_pred)
 # print(loss)
  loss.backward()
  m=model.w.grad
  n=model.b.grad
 # print(m,n)
  with t.no_grad():
    model.w-=lr_*m
    model.b-=lr_*n
  model.w.grad.zero_()
  model.b.grad.zero_()
  print(f'epoch:{i} loss:{loss}')




epoch:0 loss:3.701827717716317
epoch:1 loss:3.6791994633070333
epoch:2 loss:3.6566118937691554
epoch:3 loss:3.6340656800481552
epoch:4 loss:3.611561508939709
epoch:5 loss:3.589100083272831
epoch:6 loss:3.5666821220298495
epoch:7 loss:3.5443083604875514
epoch:8 loss:3.521979550352259
epoch:9 loss:3.499696459888692
epoch:10 loss:3.4774598740425784
epoch:11 loss:3.4552705945568714
epoch:12 loss:3.4331294400815726
epoch:13 loss:3.4110372462770733
epoch:14 loss:3.388994865931169
epoch:15 loss:3.367003169013818
epoch:16 loss:3.3450630427528636
epoch:17 loss:3.323175391788668
epoch:18 loss:3.3013411381220275
epoch:19 loss:3.279561221280447
epoch:20 loss:3.257836598341256
epoch:21 loss:3.2361682440003867
epoch:22 loss:3.2145571506192874
epoch:23 loss:3.1930043281965723
epoch:24 loss:3.1715108043953864


In [595]:
y_train

tensor([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,

In [596]:
y

tensor(4.)

In [597]:
model.forward_pass(x_test)

tensor([[4.2983e-03],
        [1.0000e+00],
        [1.1933e-01],
        [8.7902e-01],
        [1.0000e+00],
        [1.5549e-02],
        [9.5957e-01],
        [3.0985e-01],
        [6.5771e-01],
        [9.9997e-01],
        [3.9657e-02],
        [4.4597e-01],
        [9.9131e-01],
        [9.5152e-01],
        [6.4868e-01],
        [6.0891e-04],
        [1.9314e-01],
        [1.0000e+00],
        [6.1315e-02],
        [2.3819e-03],
        [9.9539e-01],
        [2.8735e-01],
        [9.9535e-01],
        [4.7179e-01],
        [1.0000e+00],
        [7.8664e-04],
        [2.3450e-03],
        [2.2645e-04],
        [1.5098e-04],
        [1.0000e+00],
        [4.8119e-02],
        [1.6940e-03],
        [1.9286e-02],
        [5.1874e-03],
        [9.9884e-01],
        [1.6335e-04],
        [9.9949e-01],
        [4.2818e-02],
        [3.2619e-01],
        [1.0392e-01],
        [9.3295e-01],
        [6.7980e-02],
        [1.0000e+00],
        [9.3946e-01],
        [8.7742e-02],
        [9

In [608]:
with t.no_grad():
  y_pred=model.forward_pass(x_test)
  y_pred=(y_pred>0.5).int()
print(y_pred)

tensor([[0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],

In [607]:
#accuracy
with t.no_grad():
  accuracy=(y_pred==y_test).float().mean()
print(f"accuracy:={accuracy}")

accuracy:=0.5443213582038879
